acme_store_homepage:
    pattern:  /store
    defaults: { _controller: AcmeStoreBundle:Default:index }

store_create:
    pattern: /store/create
    defaults: { _controller: AcmeStoreBundle:Default:create }

store_show:
    pattern: /store/show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show, id:1 }
