hello:
  pattern:	/hello/{first_name}/{last_name}
  defaults: { _controller: AcmeHelloBundle:Hello:index, color: green}

blog_show:
  pattern: /blog/{slug}
  defaults: { _controller: AcmeBlogBundle:Blog:show }

#  resource: "@AcmeHelloBundle/Resources/config/routing.yml"
#  prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
