hello:
  pattern:	/hello/{first_name}/{last_name}
  defaults: { _controller: AcmeHelloBundle:Hello:index, color: green}

blog:
  pattern: /blog/{page}
  defaults: { _controller: BlogBundle:Blog:index, page: 1}
  requirements:
    page: \d+

blog_show:
  pattern: /blog/{slug}
  defaults: { _controller: BlogBundle:Blog:show, slug: 'mäh' }

homepage:
  pattern: /{culture}
  defaults: { _controller: BlogBundle:Blog:homepage, culture: en}
  requirements:
    culture: en|de|fr


contact:
  pattern: /contact
  defaults: { _controller: BlogBundle:Blog:contact }
  requirements:
    _method: get

contact_process:
  pattern: /contact
  defaults: { _controller: BlogBundle:Blog:contactProcess }
  requirements:
    _method: post


#  resource: "@AcmeHelloBundle/Resources/config/routing.yml"
#  prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
