acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

hello:
  pattern:	/hello/{first_name}/{last_name}
  defaults: { _controller: AcmeHelloBundle:Hello:index, color: green}

blog:
  pattern: /blog/{page}
  defaults: { _controller: BlogBundle:Blog:index, page: 1}
  requirements:
    page: \d+

blog_show:
  pattern: /blog/{slug}
  defaults: { _controller: BlogBundle:Blog:show, slug: 'mäh' }

homepage:
  pattern: /{culture}
  defaults: { _controller: BlogBundle:Blog:homepage, culture: en}
  requirements:
    culture: en|de|fr

contact:
  pattern: /contact
  defaults: { _controller: BlogBundle:Blog:contact }
  requirements:
    _method: get

contact_process:
  pattern: /contact
  defaults: { _controller: BlogBundle:Blog:contactProcess }
  requirements:
    _method: post

blog:
  resource: "@BlogBundle/Resources/config/routing.yml"

gen_url:
  pattern: /gen
  defaults: { _controller: BlogBundle:Blog:genUrl }

gen_url_template:
  pattern: /gentemplate
  defaults: { _controller: BlogBundle:Blog:genUrlTemplate }


testtwig:
  resource: "@TTwigBundle/Resources/config/routing.yml"
  prefix: /ttwig
