article_show:
  pattern: /articles/{culture}/{year}/{title}.{_format}
  defaults: { _controller: BlogBundle:Article:show, _format:html }
  requirements:
    culture: en|fr|de
    year: \d+
    _format: html|rss

gen_url:
  pattern: /gen
  defaults: { _controller: BlogBundle:Article:genUrl }
